# Show more debug info on console?
debug: true
# Show packs when player joins? Permission still required.
showOnJoin: true
header: |-
  
  &6&lResource Packs:
footer: ' '
default:
  # This is the default for all resource packs.
  # All settings can be overridden by each individual pack.
  displayName: 'NoName'
  url: 'NoURL'
  hash: 'NoHash'
  permission: ''
  messages:
    # Placeholders:
    # {key} Resource pack section name.
    # {name} Resource pack display name.
    # {url} Resource pack url.
    # Make empty string to skip.
    description: '&e- &6{name} '
    use: '&6[Use]'
    always: '&6[Always]'
    disable: '&c[Disable]'
    download: '&9[&nDownload&9]'

resourcePacks:
  # Edit as needed. Add one section per pack.
  myResourcePack:
    displayName: "&dEpic Pack"
    url: 'https://www.your.url/resourcepack.zip'
    hash: '4d1e0539ffd9dbbc8618616114685de1c71eae84'
    # Keep empty to skip check.
    permission: ''
