main: com.cavetale.resourcepack.ResourcePackPlugin
name: ResourcePack

version: 0.1
api-version: 1.19

description: Use Cavetale Resource Pack
author: StarTux
website: https://github.com/StarTux/ResourcePack

depend: [Core, Connect]
softdepend: []

commands:

  resourcepack:
    aliases: [rp]
    description: Send the resource pack
    permission: resourcepack.command
    usage: /resourcepack

  resourcepackadmin:
    aliases: [rpadm]
    description: Admin commands
    permission: resourcepack.admin
    usage: /rpadm

permissions:

  resourcepack.command:
    description: Use /resourcepack
    default: op

  resourcepack.send:
    description: "Send the resource pack if they don't have it yet"
    default: false

  resourcepack.send.switch:
    description: Send the resource when switching servers if it updated
    default: false

  resourcepack.send.failed:
    description: Send the resource again when it fails to download
    default: false

  resourcepack.send.update:
    description: Send the resource pack when it updates
    default: false

  resourcepack.reset:
    description: Reset your resource pack
    default: op

  resourcepack.admin:
    description: Use /rpadm
    default: op
    children:
      resourcepack.reset: true