main: com.cavetale.resourcepack.ResourcePackPlugin
name: ResourcePack
version: 0.1
api-version: 1.13
description: Offer players to use your resource pack(s).
author: StarTux
website: https://github.com/StarTux/ResourcePack
depend: []
softdepend: []
commands:
  resourcepack:
    aliases: [rp]
    description: ResourcePack Command
    permission: resourcepack.resourcepack
    usage: /<command>
permissions:
  resourcepack.resourcepack:
    description: Use /resourcepack
    default: true
  resourcepack.admin:
    description: Use admin commands
    default: op
