main: com.cavetale.resourcepack.ResourcePackPlugin
name: ResourcePack
version: 0.1
api-version: 1.13
description: Use Cavetale Resource Pack
author: StarTux
website: https://github.com/StarTux/ResourcePack
depend: [Connect]
softdepend: []
commands:

  resourcepack:
    aliases: [rp]
    description: Send the resource pack
    permission: resourcepack.command
    usage: /resourcepack

permissions:

  resourcepack.command:
    description: Use /resourcepack
    default: op

  resourcepack.send:
    description: Send the resource pack on join
    default: false

  resourcepack.resend:
    description: Send the resource pack when it updates
    default: false
